export const PATIENT_LOGIN_FORM_SUBMITTED = 'PATIENT_LOGIN_FORM_SUBMITTED';
export const PATIENT_REGISTRATION_FORM_SUBMITTED = 'PATIENT_REGISTRATION_FORM_SUBMITTED';
export const PATIENT_LOGIN_SUCCESS = 'PATIENT_LOGIN_SUCCESS';
export const PATIENT_LOGIN_FAILED = 'PATIENT_LOGIN_FAILED';
export const PATIENT_REGISTRATION_FAILED = 'PATIENT_REGISTRATION_FAILED';